### ISSUE TITLE
Invalid boost version to compile

### ISSUE THREAD

**Issue by alexander-schranz** [procrash/petya-green-multicore#2]
With which boost version was this build? Tried several but without success. 
In the cmake it is `1.45.0` but gpu_code.hpp depends on `#include <boost/container/vector.hpp>`  which exist only since `1.48.0`

I use vc14 compiler to build from http://landinghub.visualstudio.com/visual-cpp-build-tools. 

Boost versions I tried without success:

 - 1.44.0 (boost/container/vector not found)
 - 1.45.0 (not able to build with vc14)
 - 1.46.1 (boost/container/vector not found)
 - 1.49.0 (boost/thread/xtime.hpp(23))
 - 1.62.0 (boost/chrono/duration.hpp(405) error boost::common_type<int_least64_t>)

**Comment by procrash** [comment]
I used versin 1.62 I think....

**Comment by alexander-schranz** [comment]
@procrash thx did got it to work in my fork on boost `1.45.0`: https://github.com/alexander-schranz/petya-green-multicore (there are some branches for Windows / Ubuntu ...) where I did remove the UI things as it did look incomplete for me.

But after decrypt the HDD was not bootable any suggestion to fix that?

**Comment by procrash** [comment]
Yep. You need to repair the drive with my harddisk repair application as the original code from Petya contained an error and messed up the MFT.
I'll send you the link tonight

**Comment by procrash** [comment]
Oh wait, found it directly. It's here: https://github.com/procrash/petya_cpu_filedecryption
